name: user_repository
description: This repo to handles users.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.9.2
  # firebase_storage: ^11.6.0

  # Additional dependencies can be added here
  # equatable: ^2.0.5
  rxdart: ^0.27.7
  # path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
